apiVersion: apps/v1
kind: Deployment

metadata:
  name: nasa-app1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nasa-app1

  template:
    metadata:
      labels:
        app: nasa-app1

    spec:
      containers:
        - name: nasa-app1
          image: nasa-app:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000